Homework 2 - fizzbuzz and temperature converter
Borgaard/JS-SF-8-homework pull request #22
Opened 2017-09-26 01:45 UTC by DanPitrowiski

Also there were some slight updates to past homework and files

2017-10-03 01:55 UTC, DanPitrowiski commented
Homework 3 has been added to.

2017-10-10 02:00 UTC, DanPitrowiski commented
Changed the `index.html` file to reference homework 1 for my homework :dancer:

2017-10-19 04:17 UTC, Borgaard requested changes
Let's get your .DS_Store file situation sorted. I can't accept this pull request because that file is creating a merge conflict. 

.DS_Store is a hidden metadata file containing information about your homework folder, which we don't want because it's different for everyone and causes merge conflicts like this one.

We can do it before or after class, but I'd like to get it done before accepting your pull request. If you'd like to do it on your own, here's what you need to do:

- navigate to your homework directory
- `$ ls -la` to see your hidden files - they all start with a dot `.`.
-`$ git rm --cached .DS_Store` to delete the .DS_Store file in your root homework directory (```~/JSD/JS-SF-8-homework/.DS_Store```)
- `touch .gitignore` to create a special hidden file to prevent git from tracking certain files.
- open .gitignore and add the following 3 lines:
```
.DS_Store
*.DS_Store
.DS_Store?
```

When you've done that, git add, commit, and push. This will automatically update your pull request and you don't have to do anything more. You're all set! 😋 

Optional bonus, to always ignore .DS_Store files everywhere:
`$ echo .DS_Store >> ~/.gitignore_global` this creates a global ignore file and writes .DS_Store to it.
`git config --global core.excludesfile ~/.gitignore_global` to let git you want to use this file for all of your repositories.

2017-10-23 00:52 UTC, DanPitrowiski commented
@Borgaard ok - changes have been made. I just removed `.DS_Store` all together. Should be good now :+1:

2017-11-08 23:18 UTC, Borgaard commented on danpitrowiski/README.md
> +# whiski.github.io
Leads to a 404 :P 
I was expecting something else with a url like that!

2017-11-09 02:52 UTC, Borgaard commented on danpitrowiski/hw1-madlibs/index.html
> +  <script src='https://code.jquery.com/jquery-latest.min.js'></script>
Nice catch 😜

2017-11-09 03:06 UTC, merged