Submitting Homework 3
Borgaard/JS-SF-8-homework pull request #24
Opened 2017-10-03 00:44 UTC by gnurt79

2017-10-19 06:21 UTC, Borgaard requested changes
Let's get your .DS_Store file situation sorted. I can't accept this pull request because that file is creating a merge conflict. 

.DS_Store is a hidden metadata file containing information about your homework folder, which we don't want because it's different for everyone and causes merge conflicts like this one.

We can do it before or after class, but I'd like to get it done before accepting your pull request. If you'd like to do it on your own, here's what you need to do:

- navigate to your homework directory
- `$ ls -la` to see your hidden files - they all start with a dot `.`.
-`$ git rm --cached .DS_Store` to delete the .DS_Store file in your root homework directory (```~/JSD/JS-SF-8-homework/.DS_Store```)
- `touch .gitignore` to create a special hidden file to prevent git from tracking certain files.
- open .gitignore and add the following 3 lines:
```
.DS_Store
*.DS_Store
.DS_Store?
```

When you've done that, git add, commit, and push. This will automatically update your pull request and you don't have to do anything more. You're all set! 😋 

Optional bonus, to always ignore .DS_Store files everywhere:
`$ echo .DS_Store >> ~/.gitignore_global` this creates a global ignore file and writes .DS_Store to it.
`git config --global core.excludesfile ~/.gitignore_global` to let git you want to use this file for all of your repositories.

2017-10-22 16:40 UTC, gnurt79 commented
@Borgaard Okay, I followed the steps above and re-submitted the homeworks.

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-4/madlib-with-loops/js/madlib-console.js
> +let printBtn = document.querySelector('#print');
I'm thrilled you're using `let` because of its block scoping abilities, but any reason every other variable is `var` in this madlibs file?

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-4/madlib-with-loops/js/madlib-console.js
> +  });
Neatly organized and concise responsibilities for each listener. Keep it up! 👍

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/example.js
> +		var clientKey = "js-9qZHzu2Flc59Eq5rx10JdKERovBlJp3TQ3ApyC4TOa3tA8U7aVRnFwf41RpLgtE7";
Be sure to remove API keys when pushing - often a service will disable that key if it's found to be compromised or exposed on Github.

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/example.js
> +			{
JavaScript has this neat feature called automatic semicolon insertion, or ASI. A semicolon in JS is the same as a period - when you've finished your statement, it's syntactically correct to end with a period. When JS thinks you meant to finish a statement, it'll be helpful and use ASI to add a semicolon for you when the code runs. 

As a practical example, here's what happens:
```javascript
function foo() // since a codeblock wasn't opened here, JS inserts a semicolon to stop the code.
{
  return // same as above; since nothing immediately followed the return statement, JS says, "okay, returning nothing." even though you have content to return on the next line.
  {
    bar: 1
  };    
};

console.log(foo()); // => undefined
```

The signature of an if/else conditional begins the codeblock on the same line as the statement, and ends at the same indentation where the conditional began. 

```javascript
if (true) {
   return "This is known as Egyptian bracket notation.";
}
```

When you open a statement's curly bracket on the next line, you're giving ASI a chance to stop your code from running as you would expect. Prevent this by using Egyptian bracket notation. 😋

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/example.js
> +								errorDiv.text(json.error_msg);
You're doing great keeping your code well documented with comments. That'll serve future-Trung well when you come back to look at your old code, and also makes it easier for others to figure out what's going on. 💯

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/example.js
> +				{
D:
`} else {`

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/main.js
> +const OWM_API_KEY = "";
Nice catch hiding your API key here. 👍

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/main.js
> +    var myStatusText = response.statusText;
Grabbing error log data from the source is a real smart way to handle error messages, Trung!

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/7-jquery-ajax-exercise/js/main.js
> +  var $temp = $('<h2>').html('<p> The temperature in ' + $city.val().charAt(0).toUpperCase() + $city.val().slice(1) + ', ' + $state.val().charAt(0).toUpperCase() + $state.val().charAt(1).toUpperCase(
Your editor might have a faint line about 75% of the way to the edge of your screen that shows a soft limit on how long a line of code should be, where best practice typically recommends about 80 characters long. Some editors have this by default, others require you specify column length, but I do know all editors would prefer this line be broken up, haha! 

Code isn't just for computers to read and interpret, it's for humans, too; be kind to your fellow developer reading your code! 😜

2017-11-06 20:01 UTC, Borgaard commented on trung-gnurt79/Homework-5/8-jquery-homework/js/app.js
> +    $(this).parent().remove();
Ahh!! I can't get over how fantastic this documentation is. 🌟

2017-11-06 20:02 UTC, Borgaard approved these changes

2017-11-06 20:02 UTC, merged